on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Mostrar entorno
        run: |
          echo "Usuario: $GITHUB_ACTOR"
          uname -a
      - name: Test simple
        run: |
          echo "Hola desde GitHub Actions"